### ISSUE TITLE
Interactive wapons statistics

### ISSUE THREAD

**Issue by developomp** [War-Brokers/.github#132]
- damage vs distance graph
- bullets for kill per distance
- side-by-side weapon comparison

**Comment by ZorkaA** [comment]
Are the Damage vs Distance and Bullets per Kill diagrams/stats in the weapon pages on the wiki similar to what you mean? 

Can you elaborate on the last point? What would the comparison include?

**Comment by developomp** [comment]
This feature is part of the WB hub that I'm working on. It will not be a simple wiki that lists information as is. It'll be more like a calculator with sliders and value input fields and stuff. The weapon comparison tool is a utility to compare two or more weapon's statistics such as its sway, spread, DPS, reload time, etc.

**Comment by developomp** [comment]
issue moved
